# Generated by Django 5.1.1 on 2025-06-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=256, verbose_name="Категория"),
        ),
    ]
